server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://129.211.28.148:3306/springcloud?useUnicode=true&characterEncoding=utf8
          username: root
          password: 11a85b4d6acc43538b2324e3a97548ca
          driver-class-name: com.mysql.cj.jdbc.Driver