server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://cloudeureka7001.com:7001/eureka/,http://cloudeureka7002.com:7002/eureka/,http://cloudeureka7003.com:7003/eureka/
    register-with-eureka: false

spring:
  application:
    name: springcloud-consumer-dept
