server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: cloudeureka7001.com #Eureka服务器的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false,则表示自己为注册中心
    service-url: # 监控页面
      defaultZone: http://cloudeureka7002.com:7002/eureka/,http://cloudeureka7003.com:7003/eureka/